### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by elgamal20201** [naatumach/gcode-visualizer#1]
i am trying my gcode but not work also when i uncommented your line to can see how gcode work it not stop when i close the window 
[test (5).txt](https://github.com/naatumach/gcode-visualizer/files/9333800/test.5.txt)
can you edit code to can work on this type ?

**Comment by naatumach** [comment]
Hi 
I'm not maintaining this code anymore. I'm sorry, I won't be able to help you out there. 
Thanks for reaching out
Vaibhav
